# fly.toml app configuration file generated for sifadkitabi on 2023-08-29T11:20:28+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sifadkitabi"
primary_region = "otp"

[build]
  image = "ismailkilic/datingapp:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  CloudinarySettings__CloudName = "dwguxzlir"
  CloudinarySettings__ApiKey = "125594822125742"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
